env: prod-dev

http:
  host: 0.0.0.0
  port: 8000

security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: "IgJd2x9Mae6cspfrIngu4NGuTOTEqo5k"

data:
  db:
    shortpress:
      driver: mysql
      dsn: "root:shortpress@tcp(127.0.0.1:3306)/shortpress?charset=utf8mb4&parseTime=true&loc=Local"
  blacklist:
    enabled: true
    file_path: "config/blacklist.txt"

domain:
  hosting: "mycodes.work"

storage:
  local:
    image_host: http://127.0.0.1:8000/
    video_host: http://127.0.0.1:8000/
    path: ./uploads

webhook:
  stripe:
    url: https://api.shortpress.com/api/payment/callback/stripe
  paypal:
    url: https://api.shortpress.com/api/payment/callback/paypal

log:
  log_level: info
  encoding: json           # json or console
  log_file_name: "./logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

a2e:
  generate_service_url: ${A2E_GENERATE_SERVICE_URL}
  timeout: 60s
  retry_count: 1

grok:
  base_url: ${GROK_BASE_URL}
  model: ${GROK_MODEL}
  apikey: ${GROK_API_KEY}
