// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"shortpress-server/internal/adapter/payment/stripe"
	"shortpress-server/internal/handler"
	plugins2 "shortpress-server/internal/plugins"
	"shortpress-server/internal/repository/db"
	"shortpress-server/internal/repository/db/ads"
	"shortpress-server/internal/repository/db/creator"
	"shortpress-server/internal/repository/db/payment"
	"shortpress-server/internal/repository/db/playlist"
	"shortpress-server/internal/repository/db/plugins"
	"shortpress-server/internal/repository/db/site"
	"shortpress-server/internal/repository/db/user"
	"shortpress-server/internal/repository/db/video"
	"shortpress-server/internal/server"
	"shortpress-server/internal/service"
	"shortpress-server/internal/service/analytics"
	"shortpress-server/internal/service/cache"
	"shortpress-server/internal/service/payment/coins"
	paypal3 "shortpress-server/internal/service/payment/paypal"
	stripe2 "shortpress-server/internal/service/payment/stripe"
	"shortpress-server/internal/service/payment/sub"
	"shortpress-server/pkg/app"
	"shortpress-server/pkg/blacklist"
	"shortpress-server/pkg/jwt"
	"shortpress-server/pkg/log"
	"shortpress-server/pkg/oauth2"
	"shortpress-server/pkg/server/http"
	"shortpress-server/pkg/sid"

	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	gormDB := db.NewDB(viperViper, logger)
	repository := db.NewRepository(logger, gormDB)
	transaction := db.NewTransaction(repository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	creatorRepository := creator.NewCreatorRepository(repository)
	creatorProfileRepository := creator.NewCreatorProfileRepository(repository)
	creatorSiteRepository := creator.NewCreatorWebsiteRepository(repository)
	creatorGuidesRepository := creator.NewCreatorGuidesRepository(repository)
	siteRepository := site.NewSiteRepository(repository)
	playlistRepository := playlist.NewPlaylistRepository(repository)
	videoRepository := video.NewVideoRepository(repository)
	creatorService := service.NewCreatorService(serviceService, creatorRepository, creatorProfileRepository, creatorSiteRepository, creatorGuidesRepository, siteRepository, playlistRepository, videoRepository, viperViper)
	creatorHandler := handler.NewCreatorHandler(handlerHandler, creatorService, viperViper)
	siteSeoRepository := site.NewSiteSeoRepository(repository)
	sitePlaylistsRepository := site.NewSitePlaylistRepository(repository)
	userRepository := user.NewUserRepository(repository)
	userAuthRepository := user.NewUserAuthRepository(repository)
	userCoinsRepository := payment.NewUserCoinsRepository(repository)
	paymentTransactionRepository := payment.NewPaymentTransactionRepository(repository)
	siteBuilderDataRepository := site.NewSiteBuilderDataRepository(repository)
	sitePageTemplateRepository := site.NewSitePageTemplateRepository(repository)
	blacklistBlacklist, err := blacklist.NewBlacklist(viperViper)
	if err != nil {
		return nil, nil, err
	}
	siteService := service.NewSiteService(serviceService, siteRepository, siteSeoRepository, sitePlaylistsRepository, creatorSiteRepository, playlistRepository, userRepository, userAuthRepository, userCoinsRepository, paymentTransactionRepository, siteBuilderDataRepository, sitePageTemplateRepository, blacklistBlacklist)
	siteHandler := handler.NewSiteHandler(handlerHandler, siteService)
	sitePageConfigRepository := site.NewSitePageConfigRepository(repository)
	sitePageConfigService := service.NewSitePageConfigService(serviceService, sitePageConfigRepository)
	sitePageConfigHandler := handler.NewSitePageConfigHandler(handlerHandler, sitePageConfigService)
	videoSeoRepository := video.NewVideoSeoRepository(repository)
	videoSourceRepository := video.NewVideoSourceRepository(repository)
	playlistVidRepository := playlist.NewPlaylistVidRepository(repository)
	playlistSeoRepository := playlist.NewPlaylistSeoRepository(repository)
	playlistI18nRepository := playlist.NewPlaylistI18nRepository(repository)
	playlistService := service.NewPlaylistService(serviceService, playlistRepository, playlistSeoRepository, playlistVidRepository, playlistI18nRepository, videoRepository, viperViper)
	videoService := service.NewVideoService(serviceService, videoRepository, videoSeoRepository, videoSourceRepository, playlistVidRepository, playlistService, creatorSiteRepository, viperViper)
	videoHandler := handler.NewVideoHandler(handlerHandler, videoService)
	playlistHandler := handler.NewPlaylistHandler(handlerHandler, playlistService, videoService, siteService)
	contentUnlockRepository := payment.NewContentUnlockRepository(repository)
	userPlayRecordsRepository := user.NewUserPlayRecordsRepository(repository)
	clientPlayerService := service.NewClientPlayerService(serviceService, siteRepository, sitePlaylistsRepository, videoRepository, playlistRepository, playlistI18nRepository, playlistSeoRepository, playlistVidRepository, siteSeoRepository, sitePageTemplateRepository, userRepository, contentUnlockRepository, userPlayRecordsRepository)
	siteCurrentPublishedRepository := site.NewSiteCurrentPublishedRepository(repository)
	sitePublishedHistoryRepository := site.NewSitePublishedHistoryRepository(repository)
	pagesBuilderService := service.NewPagesBuilderService(serviceService, siteBuilderDataRepository, siteCurrentPublishedRepository, sitePublishedHistoryRepository, siteRepository, sitePageTemplateRepository)
	clientPlayerHandler := handler.NewClientPlayerHandler(handlerHandler, clientPlayerService, playlistService, pagesBuilderService, viperViper)
	adRepository := ads.NewAdRepository(repository)
	adLocationRepository := ads.NewAdLocationRepository(repository)
	adsService := service.NewAdsService(serviceService, adRepository, adLocationRepository)
	adsHandler := handler.NewAdsHandler(handlerHandler, adsService)
	userProfileRepository := user.NewUserProfileRepository(repository)
	userService := service.NewUserService(serviceService, userRepository, userProfileRepository, userAuthRepository, siteRepository, userCoinsRepository, paymentTransactionRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	stripeClient := stripe.NewClient()
	paymentConfigRepository := payment.NewPaymentConfgRepository(repository)
	coinPackageRepository := payment.NewCoinPackageRepository(repository)
	webhookEventRepository := payment.NewWebhookEventRepository(repository)
	subscriptionPackageRepository := payment.NewSubscriptionPackageRepository(repository)
	userSubscriptionRepository := payment.NewUserSubscriptionRepository(repository)
	coinTransactionRepository := payment.NewCoinTransactionRepository(repository)
	coinsService := coins.NewCoinsService(logger, transaction, userCoinsRepository, coinTransactionRepository, coinPackageRepository, contentUnlockRepository, playlistRepository, userRepository, creatorRepository, videoRepository, paymentTransactionRepository)
	trackingService := analytics.NewTrackingService(viperViper, siteRepository, userRepository)
	stripeService := stripe2.NewStripeService(serviceService, viperViper, stripeClient, paymentConfigRepository, coinPackageRepository, paymentTransactionRepository, userCoinsRepository, webhookEventRepository, subscriptionPackageRepository, userRepository, userSubscriptionRepository, coinsService, trackingService)
	paypalService := paypal3.NewPaypalServiceFull(serviceService, viperViper, paymentConfigRepository, coinPackageRepository, paymentTransactionRepository, userCoinsRepository, webhookEventRepository, subscriptionPackageRepository, userRepository, userSubscriptionRepository, coinsService, trackingService)
	analyticsService := service.NewAnalyticsService(serviceService, paymentTransactionRepository, userRepository, userSubscriptionRepository)
	paymentHandler := handler.NewPaymentHandler(handlerHandler, stripeService, paypalService, coinsService, userRepository, analyticsService)
	coinsHandler := handler.NewCoinsHandler(handlerHandler, coinsService)
	coinsInternalHandler := handler.NewCoinsInternalHandler(coinsService, logger)
	subscriptionService := sub.NewSubscriptionService(serviceService, subscriptionPackageRepository, userSubscriptionRepository)
	subscriptionHandler := handler.NewSubscriptionHandler(handlerHandler, subscriptionService, stripeService, paypalService, userRepository)
	analyticsHandler := handler.NewAnalyticsHandler(handlerHandler, analyticsService)
	pagesBuilderHandler := handler.NewPagesBuilderHandler(handlerHandler, pagesBuilderService)
	a2eService := service.NewA2EService(serviceService, viperViper)
	a2eHandler := handler.NewA2EHandler(handlerHandler, a2eService)
	promptService := service.NewPromptService(serviceService)
	promptHandler := handler.NewPromptHandler(handlerHandler, promptService)
	pluginRepository := plugins.NewPluginRepository(repository)
	sitePluginRepository := plugins.NewSitePluginRepository(repository)
	pluginService := service.NewPluginService(pluginRepository, sitePluginRepository)
	pluginOrderRepository := plugins.NewPluginOrderRepository(repository)
	pluginsPlugins := plugins2.NewPlugins(userCoinsRepository, coinTransactionRepository, userRepository, pluginOrderRepository, coinPackageRepository)
	pluginHandler := handler.NewPluginHandler(handlerHandler, pluginService, pluginsPlugins, viperViper)
	v := ProvideOauthTypes()
	client := oauth2.New(v...)
	paymentBiz := service.NewPaymentBiz(serviceService, userRepository, userProfileRepository, userAuthRepository, siteRepository, client, userSubscriptionRepository, coinsService, userCoinsRepository, coinPackageRepository, subscriptionPackageRepository, paymentTransactionRepository)
	iapHandler := handler.NewIapHandler(handlerHandler, paymentBiz)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, creatorHandler, siteHandler, sitePageConfigHandler, videoHandler, playlistHandler, clientPlayerHandler, adsHandler, userHandler, paymentHandler, coinsHandler, coinsInternalHandler, subscriptionHandler, analyticsHandler, pagesBuilderHandler, a2eHandler, promptHandler, pluginHandler, iapHandler)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(db.NewDB, db.NewRepository, db.NewTransaction, creator.NewCreatorRepository, site.NewSiteRepository, site.NewSiteBuilderDataRepository, site.NewSiteCurrentPublishedRepository, site.NewSitePublishedHistoryRepository, site.NewSitePageTemplateRepository, site.NewSitePageConfigRepository, video.NewVideoRepository, video.NewVideoSeoRepository, video.NewVideoSourceRepository, playlist.NewPlaylistRepository, creator.NewCreatorProfileRepository, site.NewSiteSeoRepository, creator.NewCreatorWebsiteRepository, creator.NewCreatorGuidesRepository, site.NewSitePlaylistRepository, playlist.NewPlaylistVidRepository, playlist.NewPlaylistSeoRepository, playlist.NewPlaylistI18nRepository, ads.NewAdRepository, ads.NewAdLocationRepository, user.NewUserRepository, user.NewUserAuthRepository, user.NewUserProfileRepository, user.NewUserPlayRecordsRepository, payment.NewPaymentConfgRepository, payment.NewCoinPackageRepository, payment.NewPaymentTransactionRepository, payment.NewCoinTransactionRepository, payment.NewUserCoinsRepository, payment.NewContentUnlockRepository, payment.NewWebhookEventRepository, payment.NewSubscriptionPackageRepository, payment.NewUserSubscriptionRepository, plugins.NewPluginOrderRepository, plugins.NewPluginRepository, plugins.NewSitePluginRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewCreatorService, service.NewSiteService, service.NewSitePageConfigService, service.NewVideoService, service.NewPlaylistService, service.NewClientPlayerService, service.NewAdsService, service.NewUserService, service.NewPagesBuilderService, service.NewA2EService, service.NewPromptService, service.NewPaymentBiz, stripe.NewClient, stripe2.NewStripeService, coins.NewCoinsService, service.NewAnalyticsService, analytics.NewTrackingService, sub.NewSubscriptionService, cache.NewCacheService, cache.NewContentCacheService, service.NewPluginService)

// 插件系统
var pluginsSet = wire.NewSet(plugins2.NewPlugins)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewCreatorHandler, handler.NewSiteHandler, handler.NewSitePageConfigHandler, handler.NewVideoHandler, handler.NewPlaylistHandler, handler.NewClientPlayerHandler, handler.NewAdsHandler, handler.NewUserHandler, handler.NewPaymentHandler, handler.NewCoinsHandler, handler.NewCoinsInternalHandler, handler.NewAnalyticsHandler, handler.NewSubscriptionHandler, handler.NewPagesBuilderHandler, handler.NewA2EHandler, handler.NewPromptHandler, handler.NewPluginHandler, handler.NewIapHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

func newApp(
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("shortpress-server"))
}

// ProvideOauthTypes provides the oauth types for the oauth2 client
func ProvideOauthTypes() []oauth2.OauthType {
	return []oauth2.OauthType{oauth2.TypeGoogle, oauth2.TypeTikTok}
}
